---
kind: pipeline
type: kubernetes
name: build

x-global-variables:
  environment: &default_environment
    SRCDIR: /drone/src
    DIST_DIR: ./dist/windows

x-build_builder_image: &build_builder_image
  name: build-publish-builder-image
  image: plugins/docker
  settings:
    mtu: 1450
    repo: ${DRONE_REPO_LINK##https://}
    dockerfile: ./builder/Dockerfile
    context: ./builder/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry:
      from_secret: docker_base_url
    tags: win64
    # try to keep image small
    squash: true
    compress: true
  when:
    status:
      - success

x-upload-build-s3: &upload-build-s3
  image: minio/mc
  environment:
    <<: *default_environment
  commands:
    - WT_VERSION="$${DRONE_TAG#v}"
    - mc alias set s3_alias $${MINIO_HOST} $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY}
    - mc cp $${SRCDIR}$${DIST_DIR##.}/whispering-tiger$${WT_VERSION}_win.zip s3_alias/projects/whispering/
  when:
    ref:
      - refs/tags/*
  depends_on:
    - build-distribution-windows-package

steps:
  - <<: *build_builder_image
    name: build-publish-main-image
    when:
      branch:
        - master
        - main
  - name: build-distribution-windows-prepare
    image: ${DRONE_REPO_LINK##https://}:win64
    #pull: always  # make sure to update the image
    environment:
      <<: *default_environment
    commands:
      - echo "environments:"
      - echo "$${SRCDIR}"
      - echo "$${DIST_DIR}"
      - cd $${SRCDIR}
      - mkdir -p ./.cache
      - mkdir -p ./.cache/nltk/tokenizers
      - wget -P "./.cache/nltk/tokenizers" https://s3.libs.space:9000/ai-models/nltk/tokenizers/punkt.zip
      - unzip -o ./.cache/nltk/tokenizers/punkt.zip -d ./.cache/nltk/tokenizers
      - mkdir -p $${DIST_DIR}/
      - wget -P "$${DIST_DIR}" https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z
      - 7za x $${DIST_DIR}/ffmpeg-release-full.7z -o$${DIST_DIR}
      - rm $${DIST_DIR}/ffmpeg-release-full.7z
      - ls $${DIST_DIR}/ffmpeg-*  # Debugging: list files to be moved
      - mv $${DIST_DIR}/ffmpeg-* $${DIST_DIR}/ffmpeg
    when:
      ref:
        - refs/tags/*
  - name: build-distribution-windows
    image: ${DRONE_REPO_LINK##https://}:win64
    environment:
      <<: *default_environment
    when:
      ref:
        - refs/tags/*
    depends_on:
      - build-distribution-windows-prepare
  - name: build-distribution-windows-package
    image: ${DRONE_REPO_LINK##https://}:win64
    environment:
      <<: *default_environment
    commands:
      - cd $${SRCDIR}
      - cd $${DIST_DIR}
      - cp $${SRCDIR}/ignorelist.txt ./
      - cp $${SRCDIR}/LICENSE ./
      - cp -Rf $${SRCDIR}/websocket_clients ./
      - cp -Rf $${SRCDIR}/markers ./
      - cp -Rf $${SRCDIR}/dist_files/Plugins ./
      - cp -Rf $${SRCDIR}/dist_files/get-device-list.bat ./
      - cp -Rf $${SRCDIR}/dist_files/help.bat ./
      - cp -Rf $${SRCDIR}/dist_files/.current_platform.yaml.template ./.current_platform.yaml
      - WT_VERSION="$${DRONE_TAG#v}"
      - sed -i "s/###VERSION###/$${WT_VERSION}/g" "./.current_platform.yaml"
      #- zip -r -9 whispering-tiger$${WT_VERSION}_win.zip .
      - 7z a -tzip -mx=9 -mfb=128 whispering-tiger$${WT_VERSION}_win.zip .
    when:
      ref:
        - refs/tags/*
    depends_on:
      - build-distribution-windows
  - name: build-distribution-windows-package-hash
    image: ${DRONE_REPO_LINK##https://}:win64
    environment:
      <<: *default_environment
    commands:
      - cd $${SRCDIR}
      - cd $${DIST_DIR}
      - WT_VERSION="$${DRONE_TAG#v}"
      - hash=$$(sha256sum whispering-tiger$${WT_VERSION}_win.zip | awk '{ print $$1 }')
      - echo "SHA256 (WIN) = $$hash"
    when:
      ref:
        - refs/tags/*
    depends_on:
      - build-distribution-windows-package
  - <<: *upload-build-s3
    name: upload-s3
    environment:
      MINIO_HOST:
        from_secret: s3-endpoint-s3
      MINIO_ACCESS_KEY:
        from_secret: s3-access-key-s3
      MINIO_SECRET_KEY:
        from_secret: s3-secret-key-s3
  - <<: *upload-build-s3
    name: upload-eu
    environment:
      MINIO_HOST:
        from_secret: s3-endpoint-eu
      MINIO_ACCESS_KEY:
        from_secret: s3-access-key-eu
      MINIO_SECRET_KEY:
        from_secret: s3-secret-key-eu
  - <<: *upload-build-s3
    name: upload-us
    environment:
      MINIO_HOST:
        from_secret: s3-endpoint-us
      MINIO_ACCESS_KEY:
        from_secret: s3-access-key-us
      MINIO_SECRET_KEY:
        from_secret: s3-secret-key-us

trigger:
  #event:
  #  - tag
  ref:
    exclude:
      - refs/pipelines/*
