---
kind: pipeline
type: kubernetes
name: build

environment:
  SRCDIR: /drone/src

x-build_builder_image: &build_builder_image
  name: build-publish-builder-image
  image: plugins/docker
  settings:
    mtu: 1450
    repo: ${DRONE_REPO_LINK##https://}
    dockerfile: ./builder/Dockerfile
    context: ./builder/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry:
      from_secret: docker_base_url
    tags: win64
    # try to keep image small
    squash: true
    compress: true
  when:
    status:
      - success

steps:
  - <<: *build_builder_image
    name: build-publish-main-image
    when:
      branch:
        - master
        - main
  - name: build-distribution-windows
    image: ${DRONE_REPO_LINK##https://}:win64
    when:
      ref:
        - refs/tags/*
  - name: build-distribution-windows-package
    image: ${DRONE_REPO_LINK##https://}:win64
    commands:
      - cd ${SRCDIR}/dist
      - cp ../ignorelist.txt ./
      - cp ../LICENSE ./
      - cp -Rf ../websocket_clients ./
      - cp -Rf ../markers ./
      - wget -P "./" https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z
      - 7za x ./ffmpeg-release-full.7z -o./
      - mv ./ffmpeg-* ./ffmpeg
      - rm ./ffmpeg-release-full.7z
      - cp -Rf ../dist_files/Plugins ./
      - cp -Rf ../dist_files/get-defice-list.bat ./
      - cp -Rf ../dist_files/help.bat ./
      - cp -Rf ../dist_files/.current_platform.yaml.template ./.current_platform.yaml
      - WT_VERSION="${DRONE_TAG#v}"
      - sed -i "s/###VERSION###/$${WT_VERSION}/g" "./.current_platform.yaml"
      - zip -r -9 whispering-tiger$${WT_VERSION}_win.zip .
    when:
      ref:
        - refs/tags/*
  - name: upload
    image: plugins/s3
    settings:
      bucket:
        from_secret: s3-bucket
      access_key:
        from_secret: s3-access-key
      secret_key:
        from_secret: s3-secret-key
      source: /drone/src/dist/whispering-tiger*.zip
      target:
        from_secret: s3-target-location
    when:
      ref:
        - refs/tags/*

trigger:
  #event:
  #  - tag
  ref:
    exclude:
      - refs/pipelines/*
