# F5-TTS | E2-TTS
model = "F5-TTS"
ref_audio = "tests/ref_audio/test_en_1_ref_short.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = "Some call me nature, others call me mother nature."
gen_text = "I don't really care what you call me. I've been a silent spectator, watching species evolve, empires rise and fall. But always remember, I am mighty and enduring. Respect me and I'll nurture you; ignore me and you shall face the consequences."
# File with text to generate. Ignores the text above.
gen_file = ""
remove_silence = false
output_dir = "tests"